name: CI/CD

on:
  push:
    # branches: [main]
    tags: ["v*.*.*"]
  # pull_request:
  #   branches: [main]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    needs: [golangci]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Initialize Go module
        run: |
          go mod init nrmgo
          go mod tidy
      - name: Set Version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=$(git describe --tags --always --dirty)" >> $GITHUB_ENV
          fi
      - name: Build all platforms
        run: make build-all VERSION=${{ env.VERSION }}
      - name: Create archives and checksums
        run: |
          cd bin
          # Create archives
          for dir in nrmgo-*; do
            if [[ "$dir" == *windows* ]]; then
              zip -r "${dir}.zip" "$dir"
            else
              tar czf "${dir}.tar.gz" "$dir"
            fi
          done

          # Create SHA256 checksums
          echo "# SHA256 Checksums" > SHA256SUMS.txt
          sha256sum *.zip *.tar.gz >> SHA256SUMS.txt
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/*.zip
            bin/*.tar.gz
            bin/SHA256SUMS.txt
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## What's Changed

            ### Features
            - Add support for bun package manager
            - Add `backup` command for configuration file backup and restoration
            - Add `config` command for configuration file initialization and viewing
            - Add automatic retry mechanism to improve network request stability

            ### Enhancements
            - Optimize registry latency testing algorithm
            - Improve readability of error messages
            - Optimize command execution concurrency control
            - Improve configuration file read/write performance

            ### Bug Fixes
            - Fix path parsing issues on Windows systems
            - Fix memory leaks during concurrent requests

            ## Installation

            Download the appropriate version for your platform from the releases page:

            - Windows: `nrmgo-windows-*.zip`
            - macOS: `nrmgo-darwin-*.tar.gz`
            - Linux: `nrmgo-linux-*.tar.gz`

            Verify the SHA256 checksum of the downloaded file against `SHA256SUMS.txt`.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
